// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Product struct {
	ID          string     `json:"id"`
	Name        string     `json:"name"`
	Description *string    `json:"description,omitempty"`
	CategoryID  int32      `json:"category_id"`
	BrandID     int32      `json:"brand_id"`
	Variants    []*Variant `json:"variants"`
}

type Query struct {
}

type SearchInput struct {
	Name     *string  `json:"name,omitempty"`
	MinPrice *float64 `json:"minPrice,omitempty"`
	MaxPrice *float64 `json:"maxPrice,omitempty"`
	Page     *int32   `json:"page,omitempty"`
	Limit    *int32   `json:"limit,omitempty"`
}

type SearchResponse struct {
	Products []*Product `json:"products"`
	Total    int32      `json:"total"`
	Page     int32      `json:"page"`
	Limit    int32      `json:"limit"`
	Pages    int32      `json:"pages"`
}

type Variant struct {
	VariantID string   `json:"variant_id"`
	Sku       string   `json:"sku"`
	Price     float64  `json:"price"`
	Sizes     []int32  `json:"sizes"`
	Colors    []string `json:"colors"`
	Material  *string  `json:"material,omitempty"`
	Stock     int32    `json:"stock"`
	Rating    float64  `json:"rating"`
}
